In [25]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [4,3,3]])
b = np.array([[1,2,3], [4,5,6], [4,3,3]])
print("array: \n",arr)
aa = a+5
bb = b-4
print("array a ga 5 qoshildi: \n",aa)
print("array b dan 5 ayrildi: \n",bb)
c = aa+bb
print("array ga array qoshildi: \n",c)
print("-------------")
print("size: ",aa.size)
print("shape: ",aa.shape)


array: 
 [[1 2 3]
 [4 5 6]
 [4 3 3]]
array a ga 5 qoshildi: 
 [[ 6  7  8]
 [ 9 10 11]
 [ 9  8  8]]
array b dan 5 ayrildi: 
 [[-3 -2 -1]
 [ 0  1  2]
 [ 0 -1 -1]]
array ga array qoshildi: 
 [[ 3  5  7]
 [ 9 11 13]
 [ 9  7  7]]
-------------
size:  9
shape:  (3, 3)
